"""Initial migrations

Revision ID: a2d715381000
Revises: 
Create Date: 2025-05-17 12:30:04.734663

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a2d715381000'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_projects_id'), 'projects', ['id'], unique=False)
    op.create_table('teams',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_teams_id'), 'teams', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('agents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('jwt', sa.String(), nullable=False),
    sa.Column('creator_id', sa.UUID(), nullable=True),
    sa.Column('input_parameters', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_invoked_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['creator_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('jwt')
    )
    op.create_index(op.f('ix_agents_creator_id'), 'agents', ['creator_id'], unique=False)
    op.create_index(op.f('ix_agents_id'), 'agents', ['id'], unique=False)
    op.create_table('agentworkflows',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('flow', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('creator_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['creator_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agentworkflows_creator_id'), 'agentworkflows', ['creator_id'], unique=False)
    op.create_index(op.f('ix_agentworkflows_id'), 'agentworkflows', ['id'], unique=False)
    op.create_table('files',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=True),
    sa.Column('request_id', sa.UUID(), nullable=True),
    sa.Column('creator_id', sa.UUID(), nullable=True),
    sa.Column('mimetype', sa.String(), nullable=False),
    sa.Column('original_name', sa.String(), nullable=False),
    sa.Column('internal_name', sa.String(), nullable=False),
    sa.Column('internal_id', sa.UUID(), nullable=False),
    sa.Column('from_agent', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['creator_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_files_creator_id'), 'files', ['creator_id'], unique=False)
    op.create_index(op.f('ix_files_id'), 'files', ['id'], unique=False)
    op.create_index(op.f('ix_files_internal_id'), 'files', ['internal_id'], unique=False)
    op.create_index(op.f('ix_files_request_id'), 'files', ['request_id'], unique=False)
    op.create_index(op.f('ix_files_session_id'), 'files', ['session_id'], unique=False)
    op.create_table('logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('request_id', sa.UUID(), nullable=False),
    sa.Column('agent_id', sa.String(), nullable=True),
    sa.Column('creator_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('message', sa.String(), nullable=False),
    sa.Column('log_level', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['creator_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_logs_agent_id'), 'logs', ['agent_id'], unique=False)
    op.create_index(op.f('ix_logs_creator_id'), 'logs', ['creator_id'], unique=False)
    op.create_index(op.f('ix_logs_id'), 'logs', ['id'], unique=False)
    op.create_index(op.f('ix_logs_request_id'), 'logs', ['request_id'], unique=False)
    op.create_index(op.f('ix_logs_session_id'), 'logs', ['session_id'], unique=False)
    op.create_table('modelconfigs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('model', sa.String(), nullable=False),
    sa.Column('provider', sa.String(), nullable=False),
    sa.Column('system_prompt', sa.String(), nullable=False),
    sa.Column('temperature', sa.Float(), nullable=False),
    sa.Column('credentials', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('creator_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['creator_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_modelconfigs_creator_id'), 'modelconfigs', ['creator_id'], unique=False)
    op.create_index(op.f('ix_modelconfigs_id'), 'modelconfigs', ['id'], unique=False)
    op.create_index(op.f('ix_modelconfigs_model'), 'modelconfigs', ['model'], unique=False)
    op.create_index(op.f('ix_modelconfigs_provider'), 'modelconfigs', ['provider'], unique=False)
    op.create_table('user_project_associations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_project_associations_id'), 'user_project_associations', ['id'], unique=False)
    op.create_index(op.f('ix_user_project_associations_project_id'), 'user_project_associations', ['project_id'], unique=False)
    op.create_index(op.f('ix_user_project_associations_user_id'), 'user_project_associations', ['user_id'], unique=False)
    op.create_table('user_team_associations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('team_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_team_associations_id'), 'user_team_associations', ['id'], unique=False)
    op.create_index(op.f('ix_user_team_associations_team_id'), 'user_team_associations', ['team_id'], unique=False)
    op.create_index(op.f('ix_user_team_associations_user_id'), 'user_team_associations', ['user_id'], unique=False)
    op.create_table('agent_project_associations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('agent_id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_project_associations_agent_id'), 'agent_project_associations', ['agent_id'], unique=False)
    op.create_index(op.f('ix_agent_project_associations_id'), 'agent_project_associations', ['id'], unique=False)
    op.create_index(op.f('ix_agent_project_associations_project_id'), 'agent_project_associations', ['project_id'], unique=False)
    op.create_table('agentflow_project_associations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('flow_id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['flow_id'], ['agentworkflows.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agentflow_project_associations_flow_id'), 'agentflow_project_associations', ['flow_id'], unique=False)
    op.create_index(op.f('ix_agentflow_project_associations_id'), 'agentflow_project_associations', ['id'], unique=False)
    op.create_index(op.f('ix_agentflow_project_associations_project_id'), 'agentflow_project_associations', ['project_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_agentflow_project_associations_project_id'), table_name='agentflow_project_associations')
    op.drop_index(op.f('ix_agentflow_project_associations_id'), table_name='agentflow_project_associations')
    op.drop_index(op.f('ix_agentflow_project_associations_flow_id'), table_name='agentflow_project_associations')
    op.drop_table('agentflow_project_associations')
    op.drop_index(op.f('ix_agent_project_associations_project_id'), table_name='agent_project_associations')
    op.drop_index(op.f('ix_agent_project_associations_id'), table_name='agent_project_associations')
    op.drop_index(op.f('ix_agent_project_associations_agent_id'), table_name='agent_project_associations')
    op.drop_table('agent_project_associations')
    op.drop_index(op.f('ix_user_team_associations_user_id'), table_name='user_team_associations')
    op.drop_index(op.f('ix_user_team_associations_team_id'), table_name='user_team_associations')
    op.drop_index(op.f('ix_user_team_associations_id'), table_name='user_team_associations')
    op.drop_table('user_team_associations')
    op.drop_index(op.f('ix_user_project_associations_user_id'), table_name='user_project_associations')
    op.drop_index(op.f('ix_user_project_associations_project_id'), table_name='user_project_associations')
    op.drop_index(op.f('ix_user_project_associations_id'), table_name='user_project_associations')
    op.drop_table('user_project_associations')
    op.drop_index(op.f('ix_modelconfigs_provider'), table_name='modelconfigs')
    op.drop_index(op.f('ix_modelconfigs_model'), table_name='modelconfigs')
    op.drop_index(op.f('ix_modelconfigs_id'), table_name='modelconfigs')
    op.drop_index(op.f('ix_modelconfigs_creator_id'), table_name='modelconfigs')
    op.drop_table('modelconfigs')
    op.drop_index(op.f('ix_logs_session_id'), table_name='logs')
    op.drop_index(op.f('ix_logs_request_id'), table_name='logs')
    op.drop_index(op.f('ix_logs_id'), table_name='logs')
    op.drop_index(op.f('ix_logs_creator_id'), table_name='logs')
    op.drop_index(op.f('ix_logs_agent_id'), table_name='logs')
    op.drop_table('logs')
    op.drop_index(op.f('ix_files_session_id'), table_name='files')
    op.drop_index(op.f('ix_files_request_id'), table_name='files')
    op.drop_index(op.f('ix_files_internal_id'), table_name='files')
    op.drop_index(op.f('ix_files_id'), table_name='files')
    op.drop_index(op.f('ix_files_creator_id'), table_name='files')
    op.drop_table('files')
    op.drop_index(op.f('ix_agentworkflows_id'), table_name='agentworkflows')
    op.drop_index(op.f('ix_agentworkflows_creator_id'), table_name='agentworkflows')
    op.drop_table('agentworkflows')
    op.drop_index(op.f('ix_agents_id'), table_name='agents')
    op.drop_index(op.f('ix_agents_creator_id'), table_name='agents')
    op.drop_table('agents')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_teams_id'), table_name='teams')
    op.drop_table('teams')
    op.drop_index(op.f('ix_projects_id'), table_name='projects')
    op.drop_table('projects')
    # ### end Alembic commands ###
